
* error

try
	- 英語で「試す」の意味

except
	- 名詞形がexceptionで「例外」の意味

import sys

try:
    a = float(sys.argv[1])
    b = float(sys.argv[2])
    print(a+b)
except:
    print('Error!')

print("end")


tryブロックの中で実行されたコードに例外が発生すると強制的にexceptに処理が移り、
メッセージが表示される
例外が起こらなかった場合は処理が途中でexceptに移ることはない
上記の例だとそのままa+bまで処理される
